"""repository local_clone_path

Revision ID: 2c5768f8ae69
Revises: 583c20a98e19
Create Date: 2026-08-16 23:32:37.855266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5768f8ae69'
down_revision: Union[str, None] = '583c20a98e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('local_clone_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'local_clone_path')
    # ### end Alembic commands ###
