"""tool_calls audit table

Revision ID: 583c20a98e19
Revises: c93901f373a5
Create Date: 2026-08-16 23:20:17.507958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '583c20a98e19'
down_revision: Union[str, None] = 'c93901f373a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('agent_type', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('denial_reason', sa.String(length=512), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['task_steps.id'], name=op.f('fk_tool_calls_step_id_task_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_tool_calls_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    op.create_index('ix_tool_calls_task_id', 'tool_calls', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_calls_task_id', table_name='tool_calls')
    op.drop_table('tool_calls')
    # ### end Alembic commands ###
