"""plans raw_llm_output

Revision ID: 6558b9d576a3
Revises: 2c5768f8ae69
Create Date: 2026-08-16 23:49:07.473844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6558b9d576a3'
down_revision: Union[str, None] = '2c5768f8ae69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('raw_llm_output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'raw_llm_output')
    # ### end Alembic commands ###
