"""execution_events and task replan_count

Revision ID: c93901f373a5
Revises: 4255cf37a6f9
Create Date: 2026-08-16 22:56:43.814551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93901f373a5'
down_revision: Union[str, None] = '4255cf37a6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_execution_events_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_events'))
    )
    op.create_index('ix_execution_events_task_id', 'execution_events', ['task_id'], unique=False)
    op.add_column('tasks', sa.Column('replan_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'replan_count')
    op.drop_index('ix_execution_events_task_id', table_name='execution_events')
    op.drop_table('execution_events')
    # ### end Alembic commands ###
